import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 960, height: 540 } });
const logs = [];
page.on('console', (m) => { if (m.type() === 'error' || m.text().startsWith('LOG')) logs.push(m.text().slice(0, 300)); });
page.on('pageerror', (e) => logs.push('pageerror: ' + e.message));
await page.addInitScript(() => { try { localStorage.setItem('rainbow-sea:quality', JSON.stringify('low')); localStorage.setItem('rainbow-sea:save', JSON.stringify({ story: { step: 3, bands: [1,1,1,1,1,1,0] } })); } catch (e) {} });
await page.goto('file://' + process.cwd() + '/test.html?debug');
await page.waitForFunction(() => !document.getElementById('go').disabled, null, { timeout: 180000 });
await page.evaluate(() => document.getElementById('go').click());
await page.waitForTimeout(2500);
const R = (s) => console.log(s);
R(await page.evaluate(() => 'story ' + __dbg.story.step + ' overlay ' + __dbg.overlayName()));
await page.evaluate(() => { const d = __dbg; const pz = d.puzzles.list.find((x) => x.id === 'motes'); const sp = pz.pos; d.player.teleport(sp.x + 1, sp.y + 0.5, sp.z + 1); pz.debug.start(); });
R(await page.evaluate(() => 'challenge ' + (__dbg.puzzles.challenge() || {}).name));
await page.keyboard.press('p'); await page.waitForTimeout(300);
R(await page.evaluate(() => 'after P: challenge ' + __dbg.puzzles.challenge() + ' prompt ' + !document.getElementById('restartp').hidden + ' "' + document.getElementById('rp-t').textContent + '"'));
await page.keyboard.press('t'); await page.waitForTimeout(1200);
R(await page.evaluate(() => 'after T: challenge ' + (__dbg.puzzles.challenge() || {}).name + ' prompt hidden ' + document.getElementById('restartp').hidden + ' overlay ' + __dbg.overlayName()));
await page.waitForTimeout(500); await page.keyboard.press('p'); await page.waitForTimeout(100);
await page.screenshot({ path: 'shot_v13_restart.png' });
const t0 = Date.now();
await page.waitForFunction(() => document.getElementById('restartp').hidden, null, { timeout: 20000 }).catch(() => {});
R(await page.evaluate(() => 'auto-hide: hidden ' + document.getElementById('restartp').hidden) + ' after ' + (Date.now() - t0) + ' ms');
await page.keyboard.press('t'); await page.waitForTimeout(600);
R(await page.evaluate(() => 'T now opens: ' + __dbg.overlayName() + ' challenge ' + __dbg.puzzles.challenge()));
await page.screenshot({ path: 'shot_v13_time.png' });
console.log(logs.filter((l) => !l.includes('stairs')).join('\n') || 'no errors');
await browser.close();
